from typing import NewType, Optional

from OCC.Core.AppCont import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.AppParCurves import *
from OCC.Core.math import *


class AppCont_Function:
	def FirstParameter(self) -> float: ...
	def GetNbOf2dPoints(self) -> int: ...
	def GetNbOf3dPoints(self) -> int: ...
	def GetNumberOfPoints(self, theNbPnt: int, theNbPnt2d: int) -> None: ...
	def LastParameter(self) -> float: ...

class AppCont_LeastSquare:
	def __init__(self, SSP: AppCont_Function, U0: float, U1: float, FirstCons: AppParCurves_Constraint, LastCons: AppParCurves_Constraint, Deg: int, NbPoints: int) -> None: ...
	def Error(self, F: float, MaxE3d: float, MaxE2d: float) -> None: ...
	def IsDone(self) -> bool: ...
	def Value(self) -> AppParCurves_MultiCurve: ...
