from typing import NewType, Optional

from OCC.Core.BSplCLib import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TColStd import *
from OCC.Core.math import *
from OCC.Core.TColgp import *
from OCC.Core.gp import *
from OCC.Core.GeomAbs import *


class BSplCLib_MultDistribution:
	BSplCLib_NonConstant: int = ...
	BSplCLib_Constant: int = ...
	BSplCLib_QuasiConstant: int = ...

class BSplCLib_KnotDistribution:
	BSplCLib_NonUniform: int = ...
	BSplCLib_Uniform: int = ...

class BSplCLib:
	@staticmethod
	def AntiBoorScheme(self, U: float, Degree: int, Knots: float, Dimension: int, Poles: float, Depth: int, Length: int, Tolerance: float) -> bool: ...
	@staticmethod
	def Bohm(self, U: float, Degree: int, N: int, Knots: float, Dimension: int, Poles: float) -> None: ...
	@staticmethod
	def BoorIndex(self, Index: int, Length: int, Depth: int) -> int: ...
	@staticmethod
	def BoorScheme(self, U: float, Degree: int, Knots: float, Dimension: int, Poles: float, Depth: int, Length: int) -> None: ...
	@staticmethod
	def BuildBSpMatrix(self, Parameters: TColStd_Array1OfReal, OrderArray: TColStd_Array1OfInteger, FlatKnots: TColStd_Array1OfReal, Degree: int, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int) -> int: ...
	@staticmethod
	def BuildBoor(self, Index: int, Length: int, Dimension: int, Poles: TColStd_Array1OfReal, LP: float) -> None: ...
	@staticmethod
	def BuildCache(self, U: float, InverseOfSpanDomain: float, PeriodicFlag: bool, Degree: int, FlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, CachePoles: TColgp_Array1OfPnt, CacheWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def BuildCache(self, U: float, InverseOfSpanDomain: float, PeriodicFlag: bool, Degree: int, FlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, CachePoles: TColgp_Array1OfPnt2d, CacheWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def BuildCache(self, theParameter: float, theSpanDomain: float, thePeriodicFlag: bool, theDegree: int, theSpanIndex: int, theFlatKnots: TColStd_Array1OfReal, thePoles: TColgp_Array1OfPnt, theWeights: TColStd_Array1OfReal, theCacheArray: TColStd_Array2OfReal) -> None: ...
	@staticmethod
	def BuildCache(self, theParameter: float, theSpanDomain: float, thePeriodicFlag: bool, theDegree: int, theSpanIndex: int, theFlatKnots: TColStd_Array1OfReal, thePoles: TColgp_Array1OfPnt2d, theWeights: TColStd_Array1OfReal, theCacheArray: TColStd_Array2OfReal) -> None: ...
	@staticmethod
	def BuildEval(self, Degree: int, Index: int, Poles: TColStd_Array1OfReal, Weights: TColStd_Array1OfReal, LP: float) -> None: ...
	@staticmethod
	def BuildEval(self, Degree: int, Index: int, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, LP: float) -> None: ...
	@staticmethod
	def BuildEval(self, Degree: int, Index: int, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, LP: float) -> None: ...
	@staticmethod
	def BuildKnots(self, Degree: int, Index: int, Periodic: bool, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, LK: float) -> None: ...
	@staticmethod
	def BuildSchoenbergPoints(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def CacheD0(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt) -> None: ...
	@staticmethod
	def CacheD0(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d) -> None: ...
	@staticmethod
	def CacheD1(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec: gp_Vec) -> None: ...
	@staticmethod
	def CacheD1(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec: gp_Vec2d) -> None: ...
	@staticmethod
	def CacheD2(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec1: gp_Vec, Vec2: gp_Vec) -> None: ...
	@staticmethod
	def CacheD2(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec1: gp_Vec2d, Vec2: gp_Vec2d) -> None: ...
	@staticmethod
	def CacheD3(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec1: gp_Vec, Vec2: gp_Vec, Vec3: gp_Vec) -> None: ...
	@staticmethod
	def CacheD3(self, U: float, Degree: int, CacheParameter: float, SpanLenght: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec1: gp_Vec2d, Vec2: gp_Vec2d, Vec3: gp_Vec2d) -> None: ...
	@staticmethod
	def CoefsD0(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt) -> None: ...
	@staticmethod
	def CoefsD0(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d) -> None: ...
	@staticmethod
	def CoefsD1(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec: gp_Vec) -> None: ...
	@staticmethod
	def CoefsD1(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec: gp_Vec2d) -> None: ...
	@staticmethod
	def CoefsD2(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec1: gp_Vec, Vec2: gp_Vec) -> None: ...
	@staticmethod
	def CoefsD2(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec1: gp_Vec2d, Vec2: gp_Vec2d) -> None: ...
	@staticmethod
	def CoefsD3(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Vec1: gp_Vec, Vec2: gp_Vec, Vec3: gp_Vec) -> None: ...
	@staticmethod
	def CoefsD3(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Vec1: gp_Vec2d, Vec2: gp_Vec2d, Vec3: gp_Vec2d) -> None: ...
	@staticmethod
	def D0(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColStd_Array1OfReal, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: float) -> None: ...
	@staticmethod
	def D0(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt) -> None: ...
	@staticmethod
	def D0(self, U: float, UIndex: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt2d) -> None: ...
	@staticmethod
	def D0(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, P: gp_Pnt) -> None: ...
	@staticmethod
	def D0(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, P: gp_Pnt2d) -> None: ...
	@staticmethod
	def D1(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColStd_Array1OfReal, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: float, V: float) -> None: ...
	@staticmethod
	def D1(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt, V: gp_Vec) -> None: ...
	@staticmethod
	def D1(self, U: float, UIndex: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt2d, V: gp_Vec2d) -> None: ...
	@staticmethod
	def D1(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, P: gp_Pnt, V: gp_Vec) -> None: ...
	@staticmethod
	def D1(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, P: gp_Pnt2d, V: gp_Vec2d) -> None: ...
	@staticmethod
	def D2(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColStd_Array1OfReal, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: float, V1: float, V2: float) -> None: ...
	@staticmethod
	def D2(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt, V1: gp_Vec, V2: gp_Vec) -> None: ...
	@staticmethod
	def D2(self, U: float, UIndex: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt2d, V1: gp_Vec2d, V2: gp_Vec2d) -> None: ...
	@staticmethod
	def D2(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, P: gp_Pnt, V1: gp_Vec, V2: gp_Vec) -> None: ...
	@staticmethod
	def D2(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, P: gp_Pnt2d, V1: gp_Vec2d, V2: gp_Vec2d) -> None: ...
	@staticmethod
	def D3(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColStd_Array1OfReal, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: float, V1: float, V2: float, V3: float) -> None: ...
	@staticmethod
	def D3(self, U: float, Index: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt, V1: gp_Vec, V2: gp_Vec, V3: gp_Vec) -> None: ...
	@staticmethod
	def D3(self, U: float, UIndex: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, P: gp_Pnt2d, V1: gp_Vec2d, V2: gp_Vec2d, V3: gp_Vec2d) -> None: ...
	@staticmethod
	def D3(self, U: float, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, P: gp_Pnt, V1: gp_Vec, V2: gp_Vec, V3: gp_Vec) -> None: ...
	@staticmethod
	def D3(self, U: float, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, P: gp_Pnt2d, V1: gp_Vec2d, V2: gp_Vec2d, V3: gp_Vec2d) -> None: ...
	@staticmethod
	def Derivative(self, Degree: int, Knots: float, Dimension: int, Length: int, Order: int, Poles: float) -> None: ...
	@staticmethod
	def Eval(self, U: float, Degree: int, Knots: float, Dimension: int, Poles: float) -> None: ...
	@staticmethod
	def Eval(self, U: float, PeriodicFlag: bool, DerivativeRequest: int, ExtrapMode: int, Degree: int, FlatKnots: TColStd_Array1OfReal, ArrayDimension: int, Poles: float, Result: float) -> None: ...
	@staticmethod
	def Eval(self, U: float, PeriodicFlag: bool, DerivativeRequest: int, ExtrapMode: int, Degree: int, FlatKnots: TColStd_Array1OfReal, ArrayDimension: int, Poles: float, Weights: float, PolesResult: float, WeightsResult: float) -> None: ...
	@staticmethod
	def Eval(self, U: float, PeriodicFlag: bool, HomogeneousFlag: bool, ExtrapMode: int, Degree: int, FlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Point: gp_Pnt, Weight: float) -> None: ...
	@staticmethod
	def Eval(self, U: float, PeriodicFlag: bool, HomogeneousFlag: bool, ExtrapMode: int, Degree: int, FlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Point: gp_Pnt2d, Weight: float) -> None: ...
	@staticmethod
	def EvalBsplineBasis(self, DerivativeOrder: int, Order: int, FlatKnots: TColStd_Array1OfReal, Parameter: float, FirstNonZeroBsplineIndex: int, BsplineBasis: math_Matrix, isPeriodic: Optional[bool]) -> int: ...
	@staticmethod
	def FactorBandedMatrix(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, PivotIndexProblem: int) -> int: ...
	@staticmethod
	def FirstUKnotIndex(self, Degree: int, Mults: TColStd_Array1OfInteger) -> int: ...
	@staticmethod
	def FlatBezierKnots(self, Degree: int) -> float: ...
	@staticmethod
	def FlatIndex(self, Degree: int, Index: int, Mults: TColStd_Array1OfInteger, Periodic: bool) -> int: ...
	@staticmethod
	def FunctionMultiply(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, PolesDimension: int, Poles: float, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: float, theStatus: int) -> None: ...
	@staticmethod
	def FunctionMultiply(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColStd_Array1OfReal, theStatus: int) -> None: ...
	@staticmethod
	def FunctionMultiply(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt2d, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColgp_Array1OfPnt2d, theStatus: int) -> None: ...
	@staticmethod
	def FunctionMultiply(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColgp_Array1OfPnt, theStatus: int) -> None: ...
	@staticmethod
	def FunctionReparameterise(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, PolesDimension: int, Poles: float, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: float, theStatus: int) -> None: ...
	@staticmethod
	def FunctionReparameterise(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColStd_Array1OfReal, theStatus: int) -> None: ...
	@staticmethod
	def FunctionReparameterise(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColgp_Array1OfPnt, theStatus: int) -> None: ...
	@staticmethod
	def FunctionReparameterise(self, Function: BSplCLib_EvaluatorFunction, BSplineDegree: int, BSplineFlatKnots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt2d, FlatKnots: TColStd_Array1OfReal, NewDegree: int, NewPoles: TColgp_Array1OfPnt2d, theStatus: int) -> None: ...
	@staticmethod
	def GetPole(self, Index: int, Length: int, Depth: int, Dimension: int, LocPoles: float, Position: int, Pole: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Hunt(self, theArray: TColStd_Array1OfReal, theX: float, theXPos: int) -> None: ...
	@staticmethod
	def IncreaseDegree(self, Degree: int, NewDegree: int, Periodic: bool, Dimension: int, Poles: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger) -> None: ...
	@staticmethod
	def IncreaseDegree(self, Degree: int, NewDegree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger) -> None: ...
	@staticmethod
	def IncreaseDegree(self, Degree: int, NewDegree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger) -> None: ...
	@staticmethod
	def IncreaseDegree(self, NewDegree: int, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def IncreaseDegree(self, NewDegree: int, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def IncreaseDegreeCountKnots(self, Degree: int, NewDegree: int, Periodic: bool, Mults: TColStd_Array1OfInteger) -> int: ...
	@staticmethod
	def InsertKnot(self, UIndex: int, U: float, UMult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def InsertKnot(self, UIndex: int, U: float, UMult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def InsertKnots(self, Degree: int, Periodic: bool, Dimension: int, Poles: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, AddKnots: TColStd_Array1OfReal, AddMults: TColStd_Array1OfInteger, NewPoles: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Epsilon: float, Add: Optional[bool]) -> None: ...
	@staticmethod
	def InsertKnots(self, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, AddKnots: TColStd_Array1OfReal, AddMults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Epsilon: float, Add: Optional[bool]) -> None: ...
	@staticmethod
	def InsertKnots(self, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, AddKnots: TColStd_Array1OfReal, AddMults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Epsilon: float, Add: Optional[bool]) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt, InversionProblem: int) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt2d, InversionProblem: int) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, InversionProblem: int) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, InversionProblem: int) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, ArrayDimension: int, Poles: float, InversionProblem: int) -> None: ...
	@staticmethod
	def Interpolate(self, Degree: int, FlatKnots: TColStd_Array1OfReal, Parameters: TColStd_Array1OfReal, ContactOrderArray: TColStd_Array1OfInteger, ArrayDimension: int, Poles: float, Weights: float, InversionProblem: int) -> None: ...
	@staticmethod
	def IsRational(self, Weights: TColStd_Array1OfReal, I1: int, I2: int, Epsilon: Optional[float]) -> bool: ...
	@staticmethod
	def KnotAnalysis(self, Degree: int, Periodic: bool, CKnots: TColStd_Array1OfReal, CMults: TColStd_Array1OfInteger, KnotForm: GeomAbs_BSplKnotDistribution, MaxKnotMult: int) -> None: ...
	@staticmethod
	def KnotForm(self, Knots: TColStd_Array1OfReal, FromK1: int, ToK2: int) -> BSplCLib_KnotDistribution: ...
	@staticmethod
	def KnotSequence(self, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, KnotSeq: TColStd_Array1OfReal, Periodic: Optional[bool]) -> None: ...
	@staticmethod
	def KnotSequence(self, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, Degree: int, Periodic: bool, KnotSeq: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def KnotSequenceLength(self, Mults: TColStd_Array1OfInteger, Degree: int, Periodic: bool) -> int: ...
	@staticmethod
	def Knots(self, KnotSeq: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, Periodic: Optional[bool]) -> None: ...
	@staticmethod
	def KnotsLength(self, KnotSeq: TColStd_Array1OfReal, Periodic: Optional[bool]) -> int: ...
	@staticmethod
	def LastUKnotIndex(self, Degree: int, Mults: TColStd_Array1OfInteger) -> int: ...
	@staticmethod
	def LocateParameter(self, Degree: int, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, U: float, IsPeriodic: bool, FromK1: int, ToK2: int, KnotIndex: int, NewU: float) -> None: ...
	@staticmethod
	def LocateParameter(self, Degree: int, Knots: TColStd_Array1OfReal, U: float, IsPeriodic: bool, FromK1: int, ToK2: int, KnotIndex: int, NewU: float) -> None: ...
	@staticmethod
	def LocateParameter(self, Degree: int, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, U: float, Periodic: bool, Index: int, NewU: float) -> None: ...
	@staticmethod
	def MaxDegree(self) -> int: ...
	@staticmethod
	def MaxKnotMult(self, Mults: TColStd_Array1OfInteger, K1: int, K2: int) -> int: ...
	@staticmethod
	def MergeBSplineKnots(self, Tolerance: float, StartValue: float, EndValue: float, Degree1: int, Knots1: TColStd_Array1OfReal, Mults1: TColStd_Array1OfInteger, Degree2: int, Knots2: TColStd_Array1OfReal, Mults2: TColStd_Array1OfInteger, NumPoles: int, NewKnots: TColStd_HArray1OfReal, NewMults: TColStd_HArray1OfInteger) -> None: ...
	@staticmethod
	def MinKnotMult(self, Mults: TColStd_Array1OfInteger, K1: int, K2: int) -> int: ...
	@staticmethod
	def MovePoint(self, U: float, Displ: gp_Vec2d, Index1: int, Index2: int, Degree: int, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, FirstIndex: int, LastIndex: int, NewPoles: TColgp_Array1OfPnt2d) -> None: ...
	@staticmethod
	def MovePoint(self, U: float, Displ: gp_Vec, Index1: int, Index2: int, Degree: int, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, FirstIndex: int, LastIndex: int, NewPoles: TColgp_Array1OfPnt) -> None: ...
	@staticmethod
	def MovePointAndTangent(self, U: float, ArrayDimension: int, Delta: float, DeltaDerivative: float, Tolerance: float, Degree: int, StartingCondition: int, EndingCondition: int, Poles: float, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, NewPoles: float, ErrorStatus: int) -> None: ...
	@staticmethod
	def MovePointAndTangent(self, U: float, Delta: gp_Vec, DeltaDerivative: gp_Vec, Tolerance: float, Degree: int, StartingCondition: int, EndingCondition: int, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt, ErrorStatus: int) -> None: ...
	@staticmethod
	def MovePointAndTangent(self, U: float, Delta: gp_Vec2d, DeltaDerivative: gp_Vec2d, Tolerance: float, Degree: int, StartingCondition: int, EndingCondition: int, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt2d, ErrorStatus: int) -> None: ...
	@staticmethod
	def MultForm(self, Mults: TColStd_Array1OfInteger, FromK1: int, ToK2: int) -> BSplCLib_MultDistribution: ...
	@staticmethod
	def NbPoles(self, Degree: int, Periodic: bool, Mults: TColStd_Array1OfInteger) -> int: ...
	@staticmethod
	def NoMults(self) -> TColStd_Array1OfInteger: ...
	@staticmethod
	def NoWeights(self) -> TColStd_Array1OfReal: ...
	@staticmethod
	def PoleIndex(self, Degree: int, Index: int, Periodic: bool, Mults: TColStd_Array1OfInteger) -> int: ...
	@staticmethod
	def PolesCoefficients(self, Poles: TColgp_Array1OfPnt2d, CachePoles: TColgp_Array1OfPnt2d) -> None: ...
	@staticmethod
	def PolesCoefficients(self, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, CachePoles: TColgp_Array1OfPnt2d, CacheWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def PolesCoefficients(self, Poles: TColgp_Array1OfPnt, CachePoles: TColgp_Array1OfPnt) -> None: ...
	@staticmethod
	def PolesCoefficients(self, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, CachePoles: TColgp_Array1OfPnt, CacheWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def PrepareInsertKnots(self, Degree: int, Periodic: bool, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, AddKnots: TColStd_Array1OfReal, AddMults: TColStd_Array1OfInteger, NbPoles: int, NbKnots: int, Epsilon: float, Add: Optional[bool]) -> bool: ...
	@staticmethod
	def PrepareTrimming(self, Degree: int, Periodic: bool, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, U1: float, U2: float, NbKnots: int, NbPoles: int) -> None: ...
	@staticmethod
	def PrepareUnperiodize(self, Degree: int, Mults: TColStd_Array1OfInteger, NbKnots: int, NbPoles: int) -> None: ...
	@staticmethod
	def RaiseMultiplicity(self, KnotIndex: int, Mult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def RaiseMultiplicity(self, KnotIndex: int, Mult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def RemoveKnot(self, Index: int, Mult: int, Degree: int, Periodic: bool, Dimension: int, Poles: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Tolerance: float) -> bool: ...
	@staticmethod
	def RemoveKnot(self, Index: int, Mult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Tolerance: float) -> bool: ...
	@staticmethod
	def RemoveKnot(self, Index: int, Mult: int, Degree: int, Periodic: bool, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, Tolerance: float) -> bool: ...
	@staticmethod
	def Reparametrize(self, U1: float, U2: float, Knots: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Resolution(self, PolesArray: float, ArrayDimension: int, NumPoles: int, Weights: TColStd_Array1OfReal, FlatKnots: TColStd_Array1OfReal, Degree: int, Tolerance3D: float, UTolerance: float) -> None: ...
	@staticmethod
	def Resolution(self, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, NumPoles: int, FlatKnots: TColStd_Array1OfReal, Degree: int, Tolerance3D: float, UTolerance: float) -> None: ...
	@staticmethod
	def Resolution(self, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, NumPoles: int, FlatKnots: TColStd_Array1OfReal, Degree: int, Tolerance3D: float, UTolerance: float) -> None: ...
	@staticmethod
	def Reverse(self, Knots: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Reverse(self, Mults: TColStd_Array1OfInteger) -> None: ...
	@staticmethod
	def Reverse(self, Poles: TColgp_Array1OfPnt, Last: int) -> None: ...
	@staticmethod
	def Reverse(self, Poles: TColgp_Array1OfPnt2d, Last: int) -> None: ...
	@staticmethod
	def Reverse(self, Weights: TColStd_Array1OfReal, Last: int) -> None: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, ArrayDimension: int, Array: float) -> int: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, Array: TColgp_Array1OfPnt2d) -> int: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, Array: TColgp_Array1OfPnt) -> int: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, HomogenousFlag: bool, ArrayDimension: int, Array: float, Weights: float) -> int: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, HomogenousFlag: bool, Array: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal) -> int: ...
	@staticmethod
	def SolveBandedSystem(self, Matrix: math_Matrix, UpperBandWidth: int, LowerBandWidth: int, HomogeneousFlag: bool, Array: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal) -> int: ...
	@staticmethod
	def TangExtendToConstraint(self, FlatKnots: TColStd_Array1OfReal, C1Coefficient: float, NumPoles: int, Poles: float, Dimension: int, Degree: int, ConstraintPoint: TColStd_Array1OfReal, Continuity: int, After: bool, NbPolesResult: int, NbKnotsRsult: int, KnotsResult: float, PolesResult: float) -> None: ...
	@staticmethod
	def Trimming(self, Degree: int, Periodic: bool, Dimension: int, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, Poles: TColStd_Array1OfReal, U1: float, U2: float, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewPoles: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Trimming(self, Degree: int, Periodic: bool, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, U1: float, U2: float, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Trimming(self, Degree: int, Periodic: bool, Knots: TColStd_Array1OfReal, Mults: TColStd_Array1OfInteger, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, U1: float, U2: float, NewKnots: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Unperiodize(self, Degree: int, Dimension: int, Mults: TColStd_Array1OfInteger, Knots: TColStd_Array1OfReal, Poles: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewKnots: TColStd_Array1OfReal, NewPoles: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Unperiodize(self, Degree: int, Mults: TColStd_Array1OfInteger, Knots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt, Weights: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewKnots: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt, NewWeights: TColStd_Array1OfReal) -> None: ...
	@staticmethod
	def Unperiodize(self, Degree: int, Mults: TColStd_Array1OfInteger, Knots: TColStd_Array1OfReal, Poles: TColgp_Array1OfPnt2d, Weights: TColStd_Array1OfReal, NewMults: TColStd_Array1OfInteger, NewKnots: TColStd_Array1OfReal, NewPoles: TColgp_Array1OfPnt2d, NewWeights: TColStd_Array1OfReal) -> None: ...

class BSplCLib_Cache(Standard_Transient):
	def __init__(self, theDegree: int, thePeriodic: bool, theFlatKnots: TColStd_Array1OfReal, thePoles2d: TColgp_Array1OfPnt2d, theWeights: Optional[TColStd_Array1OfReal]) -> None: ...
	def __init__(self, theDegree: int, thePeriodic: bool, theFlatKnots: TColStd_Array1OfReal, thePoles: TColgp_Array1OfPnt, theWeights: Optional[TColStd_Array1OfReal]) -> None: ...
	def BuildCache(self, theParameter: float, theFlatKnots: TColStd_Array1OfReal, thePoles2d: TColgp_Array1OfPnt2d, theWeights: TColStd_Array1OfReal) -> None: ...
	def BuildCache(self, theParameter: float, theFlatKnots: TColStd_Array1OfReal, thePoles: TColgp_Array1OfPnt, theWeights: Optional[TColStd_Array1OfReal]) -> None: ...
	def D0(self, theParameter: float, thePoint: gp_Pnt2d) -> None: ...
	def D0(self, theParameter: float, thePoint: gp_Pnt) -> None: ...
	def D1(self, theParameter: float, thePoint: gp_Pnt2d, theTangent: gp_Vec2d) -> None: ...
	def D1(self, theParameter: float, thePoint: gp_Pnt, theTangent: gp_Vec) -> None: ...
	def D2(self, theParameter: float, thePoint: gp_Pnt2d, theTangent: gp_Vec2d, theCurvature: gp_Vec2d) -> None: ...
	def D2(self, theParameter: float, thePoint: gp_Pnt, theTangent: gp_Vec, theCurvature: gp_Vec) -> None: ...
	def D3(self, theParameter: float, thePoint: gp_Pnt2d, theTangent: gp_Vec2d, theCurvature: gp_Vec2d, theTorsion: gp_Vec2d) -> None: ...
	def D3(self, theParameter: float, thePoint: gp_Pnt, theTangent: gp_Vec, theCurvature: gp_Vec, theTorsion: gp_Vec) -> None: ...
	def IsCacheValid(self, theParameter: float) -> bool: ...

class BSplCLib_CacheParams:
	def __init__(self, theDegree: int, thePeriodic: bool, theFlatKnots: TColStd_Array1OfReal) -> None: ...
	def IsCacheValid(self, theParameter: float) -> bool: ...
	def LocateParameter(self, theParameter: float, theFlatKnots: TColStd_Array1OfReal) -> None: ...
	def PeriodicNormalization(self, theParameter: float) -> float: ...
