from typing import NewType, Optional

from OCC.Core.HLRAppli import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.HLRBRep import *
from OCC.Core.TopoDS import *


class HLRAppli_ReflectLines:
	def GetCompoundOf3dEdges(self, type: HLRBRep_TypeOfResultingEdge, visible: bool, In3d: bool) -> TopoDS_Shape: ...
	def GetResult(self) -> TopoDS_Shape: ...
	def __init__(self, aShape: TopoDS_Shape) -> None: ...
	def Perform(self) -> None: ...
	def SetAxes(self, Nx: float, Ny: float, Nz: float, XAt: float, YAt: float, ZAt: float, XUp: float, YUp: float, ZUp: float) -> None: ...
