from typing import NewType, Optional

from OCC.Core.IGESControl import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.Transfer import *
from OCC.Core.IGESToBRep import *
from OCC.Core.XSControl import *
from OCC.Core.Interface import *
from OCC.Core.TopoDS import *
from OCC.Core.IFSelect import *
from OCC.Core.IGESData import *


class IGESControl_ActorWrite(Transfer_ActorOfFinderProcess):
	def __init__(self) -> None: ...
	def Recognize(self, start: Transfer_Finder) -> bool: ...
	def Transfer(self, start: Transfer_Finder, FP: Transfer_FinderProcess) -> Transfer_Binder: ...

class IGESControl_AlgoContainer(IGESToBRep_AlgoContainer):
	def __init__(self) -> None: ...

class IGESControl_Controller(XSControl_Controller):
	def ActorRead(self, model: Interface_InterfaceModel) -> Transfer_ActorOfTransientProcess: ...
	def Customise(self, WS: XSControl_WorkSession) -> None: ...
	def __init__(self, modefnes: Optional[bool]) -> None: ...
	@staticmethod
	def Init(self) -> bool: ...
	def NewModel(self) -> Interface_InterfaceModel: ...
	def TransferWriteShape(self, shape: TopoDS_Shape, FP: Transfer_FinderProcess, model: Interface_InterfaceModel, modetrans: Optional[int]) -> IFSelect_ReturnStatus: ...

class IGESControl_IGESBoundary(IGESToBRep_IGESBoundary):
	def Check(self, result: bool, checkclosure: bool, okCurve3d: bool, okCurve2d: bool) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, CS: IGESToBRep_CurveAndSurface) -> None: ...

class IGESControl_Reader(XSControl_Reader):
	def GetReadVisible(self) -> bool: ...
	def __init__(self) -> None: ...
	def __init__(self, WS: XSControl_WorkSession, scratch: Optional[bool]) -> None: ...
	def IGESModel(self) -> IGESData_IGESModel: ...
	def NbRootsForTransfer(self) -> int: ...
	def PrintTransferInfo(self, failwarn: IFSelect_PrintFail, mode: IFSelect_PrintCount) -> None: ...
	def SetReadVisible(self, ReadRoot: bool) -> None: ...

class IGESControl_ToolContainer(IGESToBRep_ToolContainer):
	def IGESBoundary(self) -> IGESToBRep_IGESBoundary: ...
	def __init__(self) -> None: ...

class IGESControl_Writer:
	def AddEntity(self, ent: IGESData_IGESEntity) -> bool: ...
	def AddGeom(self, geom: Standard_Transient) -> bool: ...
	def AddShape(self, sh: TopoDS_Shape) -> bool: ...
	def ComputeModel(self) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, unit: str, modecr: Optional[int]) -> None: ...
	def __init__(self, model: IGESData_IGESModel, modecr: Optional[int]) -> None: ...
	def Model(self) -> IGESData_IGESModel: ...
	def SetTransferProcess(self, TP: Transfer_FinderProcess) -> None: ...
	def TransferProcess(self) -> Transfer_FinderProcess: ...
	def Write(self, file: str, fnes: Optional[bool]) -> bool: ...
