from typing import NewType, Optional

from OCC.Core.ShapeFix import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TopoDS import *
from OCC.Core.ShapeBuild import *
from OCC.Core.Message import *
from OCC.Core.ShapeExtend import *
from OCC.Core.Geom import *
from OCC.Core.TopLoc import *
from OCC.Core.ShapeAnalysis import *
from OCC.Core.ShapeConstruct import *
from OCC.Core.Geom2d import *
from OCC.Core.TopAbs import *
from OCC.Core.TopTools import *


class ShapeFix:
	@staticmethod
	def EncodeRegularity(self, shape: TopoDS_Shape, tolang: Optional[float]) -> None: ...
	@staticmethod
	def FixVertexPosition(self, theshape: TopoDS_Shape, theTolerance: float, thecontext: ShapeBuild_ReShape) -> bool: ...
	@staticmethod
	def LeastEdgeSize(self, theshape: TopoDS_Shape) -> float: ...
	@staticmethod
	def RemoveSmallEdges(self, shape: TopoDS_Shape, Tolerance: float, context: ShapeBuild_ReShape) -> TopoDS_Shape: ...
	@staticmethod
	def SameParameter(self, shape: TopoDS_Shape, enforce: bool, preci: Optional[float], theProgress: Optional[Message_ProgressIndicator], theMsgReg: Optional[ShapeExtend_BasicMsgRegistrator]) -> bool: ...

class ShapeFix_Edge(Standard_Transient):
	def FixAddCurve3d(self, edge: TopoDS_Edge) -> bool: ...
	def FixAddPCurve(self, edge: TopoDS_Edge, face: TopoDS_Face, isSeam: bool, prec: Optional[float]) -> bool: ...
	def FixAddPCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location, isSeam: bool, prec: Optional[float]) -> bool: ...
	def FixAddPCurve(self, edge: TopoDS_Edge, face: TopoDS_Face, isSeam: bool, surfana: ShapeAnalysis_Surface, prec: Optional[float]) -> bool: ...
	def FixAddPCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location, isSeam: bool, surfana: ShapeAnalysis_Surface, prec: Optional[float]) -> bool: ...
	def FixRemoveCurve3d(self, edge: TopoDS_Edge) -> bool: ...
	def FixRemovePCurve(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
	def FixRemovePCurve(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location) -> bool: ...
	def FixReversed2d(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
	def FixReversed2d(self, edge: TopoDS_Edge, surface: Geom_Surface, location: TopLoc_Location) -> bool: ...
	def FixSameParameter(self, edge: TopoDS_Edge, tolerance: Optional[float]) -> bool: ...
	def FixSameParameter(self, edge: TopoDS_Edge, face: TopoDS_Face, tolerance: Optional[float]) -> bool: ...
	def FixVertexTolerance(self, edge: TopoDS_Edge, face: TopoDS_Face) -> bool: ...
	def FixVertexTolerance(self, edge: TopoDS_Edge) -> bool: ...
	def Projector(self) -> ShapeConstruct_ProjectCurveOnSurface: ...
	def SetContext(self, context: ShapeBuild_ReShape) -> None: ...
	def __init__(self) -> None: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_EdgeConnect:
	def Add(self, aFirst: TopoDS_Edge, aSecond: TopoDS_Edge) -> None: ...
	def Add(self, aShape: TopoDS_Shape) -> None: ...
	def Build(self) -> None: ...
	def Clear(self) -> None: ...
	def __init__(self) -> None: ...

class ShapeFix_EdgeProjAux(Standard_Transient):
	def Compute(self, preci: float) -> None: ...
	def FirstParam(self) -> float: ...
	def Init(self, F: TopoDS_Face, E: TopoDS_Edge) -> None: ...
	def IsFirstDone(self) -> bool: ...
	def IsIso(self, C: Geom2d_Curve) -> bool: ...
	def IsLastDone(self) -> bool: ...
	def LastParam(self) -> float: ...
	def __init__(self) -> None: ...
	def __init__(self, F: TopoDS_Face, E: TopoDS_Edge) -> None: ...

class ShapeFix_FaceConnect:
	def Add(self, aFirst: TopoDS_Face, aSecond: TopoDS_Face) -> bool: ...
	def Build(self, shell: TopoDS_Shell, sewtoler: float, fixtoler: float) -> TopoDS_Shell: ...
	def Clear(self) -> None: ...
	def __init__(self) -> None: ...

class ShapeFix_FreeBounds:
	def GetClosedWires(self) -> TopoDS_Compound: ...
	def GetOpenWires(self) -> TopoDS_Compound: ...
	def GetShape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def __init__(self, shape: TopoDS_Shape, sewtoler: float, closetoler: float, splitclosed: bool, splitopen: bool) -> None: ...
	def __init__(self, shape: TopoDS_Shape, closetoler: float, splitclosed: bool, splitopen: bool) -> None: ...

class ShapeFix_IntersectionTool:
	def Context(self) -> ShapeBuild_ReShape: ...
	def CutEdge(self, edge: TopoDS_Edge, pend: float, cut: float, face: TopoDS_Face, iscutline: bool) -> bool: ...
	def FixIntersectingWires(self, face: TopoDS_Face) -> bool: ...
	def FixSelfIntersectWire(self, sewd: ShapeExtend_WireData, face: TopoDS_Face, NbSplit: int, NbCut: int, NbRemoved: int) -> bool: ...
	def __init__(self, context: ShapeBuild_ReShape, preci: float, maxtol: Optional[float]) -> None: ...
	def SplitEdge(self, edge: TopoDS_Edge, param: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, preci: float) -> bool: ...

class ShapeFix_Root(Standard_Transient):
	def Context(self) -> ShapeBuild_ReShape: ...
	def LimitTolerance(self, toler: float) -> float: ...
	def MaxTolerance(self) -> float: ...
	def MinTolerance(self) -> float: ...
	def MsgRegistrator(self) -> ShapeExtend_BasicMsgRegistrator: ...
	def Precision(self) -> float: ...
	def SendFail(self, shape: TopoDS_Shape, message: Message_Msg) -> None: ...
	def SendFail(self, message: Message_Msg) -> None: ...
	def SendMsg(self, shape: TopoDS_Shape, message: Message_Msg, gravity: Optional[Message_Gravity]) -> None: ...
	def SendMsg(self, message: Message_Msg, gravity: Optional[Message_Gravity]) -> None: ...
	def SendWarning(self, shape: TopoDS_Shape, message: Message_Msg) -> None: ...
	def SendWarning(self, message: Message_Msg) -> None: ...
	def Set(self, Root: ShapeFix_Root) -> None: ...
	def SetContext(self, context: ShapeBuild_ReShape) -> None: ...
	def SetMaxTolerance(self, maxtol: float) -> None: ...
	def SetMinTolerance(self, mintol: float) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
	def SetPrecision(self, preci: float) -> None: ...
	def __init__(self) -> None: ...

class ShapeFix_ShapeTolerance:
	def LimitTolerance(self, shape: TopoDS_Shape, tmin: float, tmax: Optional[float], styp: Optional[TopAbs_ShapeEnum]) -> bool: ...
	def SetTolerance(self, shape: TopoDS_Shape, preci: float, styp: Optional[TopAbs_ShapeEnum]) -> None: ...
	def __init__(self) -> None: ...

class ShapeFix_SplitTool:
	def CutEdge(self, edge: TopoDS_Edge, pend: float, cut: float, face: TopoDS_Face, iscutline: bool) -> bool: ...
	def __init__(self) -> None: ...
	def SplitEdge(self, edge: TopoDS_Edge, param: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, tol3d: float, tol2d: float) -> bool: ...
	def SplitEdge(self, edge: TopoDS_Edge, param1: float, param2: float, vert: TopoDS_Vertex, face: TopoDS_Face, newE1: TopoDS_Edge, newE2: TopoDS_Edge, tol3d: float, tol2d: float) -> bool: ...
	def SplitEdge(self, edge: TopoDS_Edge, fp: float, V1: TopoDS_Vertex, lp: float, V2: TopoDS_Vertex, face: TopoDS_Face, SeqE: TopTools_SequenceOfShape, aNum: int, context: ShapeBuild_ReShape, tol3d: float, tol2d: float) -> bool: ...

class ShapeFix_WireVertex:
	def Analyzer(self) -> ShapeAnalysis_WireVertex: ...
	def Fix(self) -> int: ...
	def FixSame(self) -> int: ...
	def Init(self, wire: TopoDS_Wire, preci: float) -> None: ...
	def Init(self, sbwd: ShapeExtend_WireData, preci: float) -> None: ...
	def Init(self, sawv: ShapeAnalysis_WireVertex) -> None: ...
	def __init__(self) -> None: ...
	def Wire(self) -> TopoDS_Wire: ...
	def WireData(self) -> ShapeExtend_WireData: ...

class ShapeFix_ComposeShell(ShapeFix_Root):
	def DispatchWires(self, faces: TopTools_SequenceOfShape, wires: ShapeFix_SequenceOfWireSegment) -> None: ...
	def GetTransferParamTool(self) -> ShapeAnalysis_TransferParameters: ...
	def Init(self, Grid: ShapeExtend_CompositeSurface, L: TopLoc_Location, Face: TopoDS_Face, Prec: float) -> None: ...
	def Perform(self) -> bool: ...
	def Result(self) -> TopoDS_Shape: ...
	def SetTransferParamTool(self, TransferParam: ShapeAnalysis_TransferParameters) -> None: ...
	def __init__(self) -> None: ...
	def SplitEdges(self) -> None: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Face(ShapeFix_Root):
	def Add(self, wire: TopoDS_Wire) -> None: ...
	def ClearModes(self) -> None: ...
	def Face(self) -> TopoDS_Face: ...
	def FixAddNaturalBound(self) -> bool: ...
	def FixIntersectingWires(self) -> bool: ...
	def FixLoopWire(self, aResWires: TopTools_SequenceOfShape) -> bool: ...
	def FixMissingSeam(self) -> bool: ...
	def FixOrientation(self) -> bool: ...
	def FixOrientation(self, MapWires: TopTools_DataMapOfShapeListOfShape) -> bool: ...
	def FixPeriodicDegenerated(self) -> bool: ...
	def FixSmallAreaWire(self, theIsRemoveSmallFace: bool) -> bool: ...
	def FixSplitFace(self, MapWires: TopTools_DataMapOfShapeListOfShape) -> bool: ...
	def FixWireTool(self) -> ShapeFix_Wire: ...
	def FixWiresTwoCoincEdges(self) -> bool: ...
	def Init(self, face: TopoDS_Face) -> None: ...
	def Init(self, surf: Geom_Surface, preci: float, fwd: Optional[bool]) -> None: ...
	def Init(self, surf: ShapeAnalysis_Surface, preci: float, fwd: Optional[bool]) -> None: ...
	def Perform(self) -> bool: ...
	def Result(self) -> TopoDS_Shape: ...
	def SetMaxTolerance(self, maxtol: float) -> None: ...
	def SetMinTolerance(self, mintol: float) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
	def SetPrecision(self, preci: float) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, face: TopoDS_Face) -> None: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_FixSmallFace(ShapeFix_Root):
	def ComputeSharedEdgeForStripFace(self, F: TopoDS_Face, E1: TopoDS_Edge, E2: TopoDS_Edge, F1: TopoDS_Face, tol: float) -> TopoDS_Edge: ...
	def FixFace(self, F: TopoDS_Face) -> TopoDS_Face: ...
	def FixPinFace(self, F: TopoDS_Face) -> bool: ...
	def FixShape(self) -> TopoDS_Shape: ...
	def FixSplitFace(self, S: TopoDS_Shape) -> TopoDS_Shape: ...
	def FixSpotFace(self) -> TopoDS_Shape: ...
	def FixStripFace(self, wasdone: Optional[bool]) -> TopoDS_Shape: ...
	def Init(self, S: TopoDS_Shape) -> None: ...
	def Perform(self) -> None: ...
	def RemoveFacesInCaseOfSpot(self, F: TopoDS_Face) -> bool: ...
	def RemoveFacesInCaseOfStrip(self, F: TopoDS_Face) -> bool: ...
	def ReplaceInCaseOfStrip(self, F: TopoDS_Face, E1: TopoDS_Edge, E2: TopoDS_Edge, tol: float) -> bool: ...
	def ReplaceVerticesInCaseOfSpot(self, F: TopoDS_Face, tol: float) -> bool: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def SplitOneFace(self, F: TopoDS_Face, theSplittedFaces: TopoDS_Compound) -> bool: ...

class ShapeFix_FixSmallSolid(ShapeFix_Root):
	def Merge(self, theShape: TopoDS_Shape, theContext: ShapeBuild_ReShape) -> TopoDS_Shape: ...
	def Remove(self, theShape: TopoDS_Shape, theContext: ShapeBuild_ReShape) -> TopoDS_Shape: ...
	def SetFixMode(self, theMode: int) -> None: ...
	def SetVolumeThreshold(self, theThreshold: Optional[float]) -> None: ...
	def SetWidthFactorThreshold(self, theThreshold: Optional[float]) -> None: ...
	def __init__(self) -> None: ...

class ShapeFix_Shape(ShapeFix_Root):
	def FixEdgeTool(self) -> ShapeFix_Edge: ...
	def FixFaceTool(self) -> ShapeFix_Face: ...
	def FixShellTool(self) -> ShapeFix_Shell: ...
	def FixSolidTool(self) -> ShapeFix_Solid: ...
	def FixWireTool(self) -> ShapeFix_Wire: ...
	def Init(self, shape: TopoDS_Shape) -> None: ...
	def Perform(self, theProgress: Optional[Message_ProgressIndicator]) -> bool: ...
	def SetMaxTolerance(self, maxtol: float) -> None: ...
	def SetMinTolerance(self, mintol: float) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
	def SetPrecision(self, preci: float) -> None: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def __init__(self, shape: TopoDS_Shape) -> None: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Shell(ShapeFix_Root):
	def ErrorFaces(self) -> TopoDS_Compound: ...
	def FixFaceOrientation(self, shell: TopoDS_Shell, isAccountMultiConex: Optional[bool], NonManifold: Optional[bool]) -> bool: ...
	def FixFaceTool(self) -> ShapeFix_Face: ...
	def Init(self, shell: TopoDS_Shell) -> None: ...
	def NbShells(self) -> int: ...
	def Perform(self, theProgress: Optional[Message_ProgressIndicator]) -> bool: ...
	def SetMaxTolerance(self, maxtol: float) -> None: ...
	def SetMinTolerance(self, mintol: float) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
	def SetNonManifoldFlag(self, isNonManifold: bool) -> None: ...
	def SetPrecision(self, preci: float) -> None: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def __init__(self, shape: TopoDS_Shell) -> None: ...
	def Shell(self) -> TopoDS_Shell: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_Solid(ShapeFix_Root):
	def FixShellTool(self) -> ShapeFix_Shell: ...
	def Init(self, solid: TopoDS_Solid) -> None: ...
	def Perform(self, theProgress: Optional[Message_ProgressIndicator]) -> bool: ...
	def SetMaxTolerance(self, maxtol: float) -> None: ...
	def SetMinTolerance(self, mintol: float) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...
	def SetPrecision(self, preci: float) -> None: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def __init__(self, solid: TopoDS_Solid) -> None: ...
	def Solid(self) -> TopoDS_Shape: ...
	def SolidFromShell(self, shell: TopoDS_Shell) -> TopoDS_Solid: ...
	def Status(self, status: ShapeExtend_Status) -> bool: ...

class ShapeFix_SplitCommonVertex(ShapeFix_Root):
	def Init(self, S: TopoDS_Shape) -> None: ...
	def Perform(self) -> None: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...

class ShapeFix_Wire(ShapeFix_Root):
	def Analyzer(self) -> ShapeAnalysis_Wire: ...
	def ClearModes(self) -> None: ...
	def ClearStatuses(self) -> None: ...
	def Face(self) -> TopoDS_Face: ...
	def FixClosed(self, prec: Optional[float]) -> bool: ...
	def FixConnected(self, prec: Optional[float]) -> bool: ...
	def FixConnected(self, num: int, prec: float) -> bool: ...
	def FixDegenerated(self) -> bool: ...
	def FixDegenerated(self, num: int) -> bool: ...
	def FixEdgeCurves(self) -> bool: ...
	def FixEdgeTool(self) -> ShapeFix_Edge: ...
	def FixGap2d(self, num: int, convert: Optional[bool]) -> bool: ...
	def FixGap3d(self, num: int, convert: Optional[bool]) -> bool: ...
	def FixGaps2d(self) -> bool: ...
	def FixGaps3d(self) -> bool: ...
	def FixLacking(self, force: Optional[bool]) -> bool: ...
	def FixLacking(self, num: int, force: Optional[bool]) -> bool: ...
	def FixNotchedEdges(self) -> bool: ...
	def FixReorder(self) -> bool: ...
	def FixReorder(self, wi: ShapeAnalysis_WireOrder) -> bool: ...
	def FixSeam(self, num: int) -> bool: ...
	def FixSelfIntersection(self) -> bool: ...
	def FixShifted(self) -> bool: ...
	def FixSmall(self, lockvtx: bool, precsmall: Optional[float]) -> int: ...
	def FixSmall(self, num: int, lockvtx: bool, precsmall: float) -> bool: ...
	def FixTails(self) -> bool: ...
	def Init(self, wire: TopoDS_Wire, face: TopoDS_Face, prec: float) -> None: ...
	def Init(self, saw: ShapeAnalysis_Wire) -> None: ...
	def IsLoaded(self) -> bool: ...
	def IsReady(self) -> bool: ...
	def LastFixStatus(self, status: ShapeExtend_Status) -> bool: ...
	def Load(self, wire: TopoDS_Wire) -> None: ...
	def Load(self, sbwd: ShapeExtend_WireData) -> None: ...
	def NbEdges(self) -> int: ...
	def Perform(self) -> bool: ...
	def SetFace(self, face: TopoDS_Face) -> None: ...
	def SetMaxTailAngle(self, theMaxTailAngle: float) -> None: ...
	def SetMaxTailWidth(self, theMaxTailWidth: float) -> None: ...
	def SetPrecision(self, prec: float) -> None: ...
	def SetSurface(self, surf: Geom_Surface) -> None: ...
	def SetSurface(self, surf: Geom_Surface, loc: TopLoc_Location) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, wire: TopoDS_Wire, face: TopoDS_Face, prec: float) -> None: ...
	def StatusClosed(self, status: ShapeExtend_Status) -> bool: ...
	def StatusConnected(self, status: ShapeExtend_Status) -> bool: ...
	def StatusDegenerated(self, status: ShapeExtend_Status) -> bool: ...
	def StatusEdgeCurves(self, status: ShapeExtend_Status) -> bool: ...
	def StatusFixTails(self, status: ShapeExtend_Status) -> bool: ...
	def StatusGaps2d(self, status: ShapeExtend_Status) -> bool: ...
	def StatusGaps3d(self, status: ShapeExtend_Status) -> bool: ...
	def StatusLacking(self, status: ShapeExtend_Status) -> bool: ...
	def StatusNotches(self, status: ShapeExtend_Status) -> bool: ...
	def StatusRemovedSegment(self) -> bool: ...
	def StatusReorder(self, status: ShapeExtend_Status) -> bool: ...
	def StatusSelfIntersection(self, status: ShapeExtend_Status) -> bool: ...
	def StatusSmall(self, status: ShapeExtend_Status) -> bool: ...
	def Wire(self) -> TopoDS_Wire: ...
	def WireAPIMake(self) -> TopoDS_Wire: ...
	def WireData(self) -> ShapeExtend_WireData: ...

class ShapeFix_Wireframe(ShapeFix_Root):
	def CheckSmallEdges(self, theSmallEdges: TopTools_MapOfShape, theEdgeToFaces: TopTools_DataMapOfShapeListOfShape, theFaceWithSmall: TopTools_DataMapOfShapeListOfShape, theMultyEdges: TopTools_MapOfShape) -> bool: ...
	def ClearStatuses(self) -> None: ...
	def FixSmallEdges(self) -> bool: ...
	def FixWireGaps(self) -> bool: ...
	def LimitAngle(self) -> float: ...
	def Load(self, shape: TopoDS_Shape) -> None: ...
	def MergeSmallEdges(self, theSmallEdges: TopTools_MapOfShape, theEdgeToFaces: TopTools_DataMapOfShapeListOfShape, theFaceWithSmall: TopTools_DataMapOfShapeListOfShape, theMultyEdges: TopTools_MapOfShape, theModeDrop: Optional[bool], theLimitAngle: Optional[float]) -> bool: ...
	def SetLimitAngle(self, theLimitAngle: float) -> None: ...
	def Shape(self) -> TopoDS_Shape: ...
	def __init__(self) -> None: ...
	def __init__(self, shape: TopoDS_Shape) -> None: ...
	def StatusSmallEdges(self, status: ShapeExtend_Status) -> bool: ...
	def StatusWireGaps(self, status: ShapeExtend_Status) -> bool: ...
