from typing import NewType, Optional

from OCC.Core.ShapeCustom import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TopoDS import *
from OCC.Core.GeomAbs import *
from OCC.Core.Geom import *
from OCC.Core.Geom2d import *
from OCC.Core.TColgp import *
from OCC.Core.BRepTools import *
from OCC.Core.ShapeExtend import *
from OCC.Core.Message import *
from OCC.Core.TopLoc import *
from OCC.Core.gp import *


class ShapeCustom:
	@staticmethod
	def BSplineRestriction(self, S: TopoDS_Shape, Tol3d: float, Tol2d: float, MaxDegree: int, MaxNbSegment: int, Continuity3d: GeomAbs_Shape, Continuity2d: GeomAbs_Shape, Degree: bool, Rational: bool, aParameters: ShapeCustom_RestrictionParameters) -> TopoDS_Shape: ...
	@staticmethod
	def ConvertToBSpline(self, S: TopoDS_Shape, extrMode: bool, revolMode: bool, offsetMode: bool, planeMode: Optional[bool]) -> TopoDS_Shape: ...
	@staticmethod
	def ConvertToRevolution(self, S: TopoDS_Shape) -> TopoDS_Shape: ...
	@staticmethod
	def DirectFaces(self, S: TopoDS_Shape) -> TopoDS_Shape: ...
	@staticmethod
	def ScaleShape(self, S: TopoDS_Shape, scale: float) -> TopoDS_Shape: ...
	@staticmethod
	def SweptToElementary(self, S: TopoDS_Shape) -> TopoDS_Shape: ...

class ShapeCustom_Curve:
	def ConvertToPeriodic(self, substitute: bool, preci: Optional[float]) -> Geom_Curve: ...
	def Init(self, C: Geom_Curve) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, C: Geom_Curve) -> None: ...

class ShapeCustom_Curve2d:
	@staticmethod
	def ConvertToLine2d(self, theCurve: Geom2d_Curve, theFirstIn: float, theLastIn: float, theTolerance: float, theNewFirst: float, theNewLast: float, theDeviation: float) -> Geom2d_Line: ...
	@staticmethod
	def IsLinear(self, thePoles: TColgp_Array1OfPnt2d, theTolerance: float, theDeviation: float) -> bool: ...
	@staticmethod
	def SimplifyBSpline2d(self, theBSpline2d: Geom2d_BSplineCurve, theTolerance: float) -> bool: ...

class ShapeCustom_Modification(BRepTools_Modification):
	def MsgRegistrator(self) -> ShapeExtend_BasicMsgRegistrator: ...
	def SendMsg(self, shape: TopoDS_Shape, message: Message_Msg, gravity: Optional[Message_Gravity]) -> None: ...
	def SetMsgRegistrator(self, msgreg: ShapeExtend_BasicMsgRegistrator) -> None: ...

class ShapeCustom_RestrictionParameters(Standard_Transient):
	def __init__(self) -> None: ...

class ShapeCustom_Surface:
	def ConvertToAnalytical(self, tol: float, substitute: bool) -> Geom_Surface: ...
	def ConvertToPeriodic(self, substitute: bool, preci: Optional[float]) -> Geom_Surface: ...
	def Gap(self) -> float: ...
	def Init(self, S: Geom_Surface) -> None: ...
	def __init__(self) -> None: ...
	def __init__(self, S: Geom_Surface) -> None: ...

class ShapeCustom_TrsfModification(BRepTools_TrsfModification):
	def NewCurve(self, E: TopoDS_Edge, C: Geom_Curve, L: TopLoc_Location, Tol: float) -> bool: ...
	def NewCurve2d(self, E: TopoDS_Edge, F: TopoDS_Face, NewE: TopoDS_Edge, NewF: TopoDS_Face, C: Geom2d_Curve, Tol: float) -> bool: ...
	def NewParameter(self, V: TopoDS_Vertex, E: TopoDS_Edge, P: float, Tol: float) -> bool: ...
	def NewPoint(self, V: TopoDS_Vertex, P: gp_Pnt, Tol: float) -> bool: ...
	def NewSurface(self, F: TopoDS_Face, S: Geom_Surface, L: TopLoc_Location, Tol: float, RevWires: bool, RevFace: bool) -> bool: ...
	def __init__(self, T: gp_Trsf) -> None: ...

class ShapeCustom_ConvertToBSpline(ShapeCustom_Modification):
	def Continuity(self, E: TopoDS_Edge, F1: TopoDS_Face, F2: TopoDS_Face, NewE: TopoDS_Edge, NewF1: TopoDS_Face, NewF2: TopoDS_Face) -> GeomAbs_Shape: ...
	def NewCurve(self, E: TopoDS_Edge, C: Geom_Curve, L: TopLoc_Location, Tol: float) -> bool: ...
	def NewCurve2d(self, E: TopoDS_Edge, F: TopoDS_Face, NewE: TopoDS_Edge, NewF: TopoDS_Face, C: Geom2d_Curve, Tol: float) -> bool: ...
	def NewParameter(self, V: TopoDS_Vertex, E: TopoDS_Edge, P: float, Tol: float) -> bool: ...
	def NewPoint(self, V: TopoDS_Vertex, P: gp_Pnt, Tol: float) -> bool: ...
	def NewSurface(self, F: TopoDS_Face, S: Geom_Surface, L: TopLoc_Location, Tol: float, RevWires: bool, RevFace: bool) -> bool: ...
	def SetExtrusionMode(self, extrMode: bool) -> None: ...
	def SetOffsetMode(self, offsetMode: bool) -> None: ...
	def SetPlaneMode(self, planeMode: bool) -> None: ...
	def SetRevolutionMode(self, revolMode: bool) -> None: ...
	def __init__(self) -> None: ...

class ShapeCustom_DirectModification(ShapeCustom_Modification):
	def Continuity(self, E: TopoDS_Edge, F1: TopoDS_Face, F2: TopoDS_Face, NewE: TopoDS_Edge, NewF1: TopoDS_Face, NewF2: TopoDS_Face) -> GeomAbs_Shape: ...
	def NewCurve(self, E: TopoDS_Edge, C: Geom_Curve, L: TopLoc_Location, Tol: float) -> bool: ...
	def NewCurve2d(self, E: TopoDS_Edge, F: TopoDS_Face, NewE: TopoDS_Edge, NewF: TopoDS_Face, C: Geom2d_Curve, Tol: float) -> bool: ...
	def NewParameter(self, V: TopoDS_Vertex, E: TopoDS_Edge, P: float, Tol: float) -> bool: ...
	def NewPoint(self, V: TopoDS_Vertex, P: gp_Pnt, Tol: float) -> bool: ...
	def NewSurface(self, F: TopoDS_Face, S: Geom_Surface, L: TopLoc_Location, Tol: float, RevWires: bool, RevFace: bool) -> bool: ...
	def __init__(self) -> None: ...
