from typing import NewType, Optional

from OCC.Core.TopBas import *
from OCC.Core.Standard import *
from OCC.Core.NCollection import *
from OCC.Core.TopAbs import *


class TopBas_TestInterference:
	def Boundary(self, B: int) -> None: ...
	def Boundary(self) -> int: ...
	def BoundaryTransition(self, BTr: TopAbs_Orientation) -> None: ...
	def BoundaryTransition(self) -> TopAbs_Orientation: ...
	def Intersection(self, I: float) -> None: ...
	def Intersection(self) -> float: ...
	def Orientation(self, O: TopAbs_Orientation) -> None: ...
	def Orientation(self) -> TopAbs_Orientation: ...
	def __init__(self) -> None: ...
	def __init__(self, Inters: float, Bound: int, Orient: TopAbs_Orientation, Trans: TopAbs_Orientation, BTrans: TopAbs_Orientation) -> None: ...
	def Transition(self, Tr: TopAbs_Orientation) -> None: ...
	def Transition(self) -> TopAbs_Orientation: ...
